# 开发环境配置
spring:
  # 数据库配置 - 开发环境使用本地PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/napcat_manager_dev
    username: postgres
    password: 123456tpf

  # SQL初始化 - 开发环境
  sql:
    init:
      mode: always

# 日志配置 - 开发环境更详细的日志
logging:
  level:
    com.jinyue: DEBUG
    org.springframework.web.socket: DEBUG
    com.baomidou.mybatisplus: DEBUG
    org.apache.ibatis: DEBUG
    com.github.dockerjava: DEBUG

# 监控配置 - 开发环境开放更多端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# 自定义配置 - 开发环境配置
napcat:
  docker:
    host: tcp://localhost:2375
    tls-verify: false

  forwarding:
    target-url: http://localhost:8081/api/messages

  instance:
    max-instances: 10
    health-check-interval: 10000